[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"
WS_PORT = "3002"
HOST = "0.0.0.0"
CORS_ORIGINS = "${{RAILWAY_STATIC_URL}},${{RAILWAY_PUBLIC_DOMAIN}}"

[healthcheck]
path = "/health"
port = "${{PORT}}"